// web/packages/ui/src/button.tsx
import type { VariantProps } from "class-variance-authority";
import { Slot } from "@radix-ui/react-slot";
import { cva } from "class-variance-authority";

import { cn } from "@acme/ui";

const buttonVariants = cva(
  "focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive inline-flex shrink-0 items-center justify-center gap-2 rounded-md text-sm font-medium whitespace-nowrap transition-all outline-none focus-visible:ring-[3px] disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90",
        destructive:
          "bg-destructive hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60 text-white",
        outline:
          "bg-background hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50 border shadow-xs",
        secondary:
          "bg-secondary text-secondary-foreground hover:bg-secondary/80",
        ghost:
          "hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-9 px-4 py-2 has-[>svg]:px-3",
        sm: "h-8 gap-1.5 rounded-md px-3 has-[>svg]:px-2.5",
        lg: "h-10 rounded-md px-6 has-[>svg]:px-4",
        icon: "size-9",
        "icon-sm": "size-8",
        "icon-lg": "size-10",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  },
);

function Button({
  className,
  variant = "default",
  size = "default",
  asChild = false,
  ...props
}: React.ComponentProps<"button"> &
  VariantProps<typeof buttonVariants> & {
    asChild?: boolean;
  }) {
  const Comp = asChild ? Slot : "button";

  return (
    <Comp
      data-slot="button"
      data-variant={variant}
      data-size={size}
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  );
}

export { Button, buttonVariants };

// web/apps/uniapp-tw/src/components/ui/Button.vue
<script setup lang="ts">
import { computed } from 'vue'
import Icon from './Icon.vue'
import type { IconName } from '../icons/iconsRegistry'

type ButtonVariant = 'default' | 'secondary' | 'outline' | 'ghost' | 'destructive'
type ButtonSize = 'sm' | 'md' | 'lg' | 'icon'

interface Props {
  variant?: ButtonVariant
  size?: ButtonSize
  disabled?: boolean
  loading?: boolean
  iconLeft?: IconName
  iconRight?: IconName
  icon?: IconName // alias for iconLeft
  class?: string
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'default',
  size: 'md',
  disabled: false,
  loading: false,
  iconLeft: undefined,
  iconRight: undefined,
  icon: undefined,
  class: '',
})

const emit = defineEmits<{
  (e: 'click', event: MouseEvent): void
}>()

const resolvedIconLeft = computed(() => props.icon ?? props.iconLeft)
const resolvedIconRight = computed(() => props.iconRight)

const iconSize = computed(() => {
  const sizes: Record<ButtonSize, number> = { sm: 14, md: 16, lg: 18, icon: 18 }
  return sizes[props.size]
})

const buttonClass = computed(() => {
  const base =
    'inline-flex items-center justify-center gap-2 border rounded-lg font-semibold transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none active:scale-[0.97] disabled:active:scale-100 border-transparent'

  const cursor = props.loading ? 'cursor-wait' : 'cursor-pointer'
  const disabledCursor = props.disabled && !props.loading ? 'disabled:cursor-not-allowed' : ''

  const sizeClass: Record<ButtonSize, string> = {
    sm: 'h-8 px-3 text-xs rounded-md gap-1.5',
    md: 'h-10 px-4 text-sm rounded-lg',
    lg: 'h-12 px-6 text-base rounded-xl gap-2.5',
    icon: 'h-10 w-10 p-0 rounded-lg',
  }

  const variantClass: Record<ButtonVariant, string> = {
    default:
      'text-foreground border-transparent bg-[linear-gradient(135deg,var(--accent-pink-light)_0%,var(--accent-pink)_100%)] shadow-[0_2rpx_8rpx_rgba(0,0,0,0.1),0_4rpx_16rpx_color-mix(in_oklch,var(--accent-pink)_25%,transparent)] hover:shadow-[0_4rpx_12rpx_rgba(0,0,0,0.15),0_8rpx_24rpx_color-mix(in_oklch,var(--accent-pink)_35%,transparent)] focus-visible:ring-accent-pink',
    secondary:
      'text-foreground border-border bg-secondary hover:bg-[color-mix(in_oklch,var(--secondary)_85%,transparent)] focus-visible:ring-ring',
    outline:
      'text-foreground border-border bg-transparent hover:bg-accent focus-visible:ring-ring',
    ghost:
      'text-foreground bg-transparent border-transparent hover:bg-[color-mix(in_oklch,var(--foreground)_8%,transparent)] focus-visible:ring-ring',
    destructive:
      'text-white border-transparent bg-destructive shadow-[0_2rpx_8rpx_color-mix(in_oklch,var(--destructive)_30%,transparent)] hover:bg-[color-mix(in_oklch,var(--destructive)_85%,black)] focus-visible:ring-destructive',
  }

  return [
    base,
    cursor,
    disabledCursor,
    sizeClass[props.size],
    variantClass[props.variant],
    props.class,
  ]
    .filter(Boolean)
    .join(' ')
})

function handleClick(event: MouseEvent) {
  if (!props.disabled && !props.loading) {
    emit('click', event)
  }
}
</script>

<template>
  <button
    :class="buttonClass"
    :disabled="disabled || loading"
    @click="handleClick"
  >
    <!-- Loading spinner -->
    <view v-if="loading" class="flex items-center justify-center">
      <Icon name="loader" :size="iconSize" class="animate-spin duration-[1200ms]" />
    </view>

    <!-- Left icon -->
    <Icon
      v-else-if="resolvedIconLeft"
      :name="resolvedIconLeft"
      :size="iconSize"
      class="flex-shrink-0 -mr-[2rpx]"
    />

    <!-- Default slot -->
    <text v-if="$slots.default" class="inline-flex items-center justify-center">
      <slot />
    </text>

    <!-- Right icon -->
    <Icon
      v-if="resolvedIconRight && !loading"
      :name="resolvedIconRight"
      :size="iconSize"
      class="flex-shrink-0 -ml-[2rpx]"
    />
  </button>
</template>
